artsenius/test-automation-webdriverio-qa3

test/expected/global-header.js, test/specs/reg/global-header.js
=> font color

package-lock.json, test/expected/bugList.js, test/selectors/bugList.js, test/specs/reg/BugList/General/BugList-General.js, test/specs/reg/all-issues.js, test/specs/reg/global-header.js, test/specs/smoke/smoke.js, wdio.conf.js
=> Nikiforov BugList auto tests

test/expected/global-footer.js, test/selectors/global-footer.js, test/specs/reg/global-footer/design.js
Fixed the selectors, and change quotes.
=> Global footer/kim

test/expected/login.js, test/selectors/login.js, test/specs/reg/login/error.js, wdio.conf.js
https://jira.pasv.us/browse/RBTA-24
Added tests for login->error->design section.
=> RBTA-24 login error design/trusevich

test/expected/navigation.js, test/selectors/navigation-bar.js, test/specs/reg/navigationBar/general-nav-bar.js, wdio.conf.js
tests for Navigation Bar General. Please, check PR
=> RBTA-88/atambayev-daulet/navigation-bar/general

test/data/registration.js, test/expected/registration.js, test/helpers/helpers.js, test/selectors/registration.js, test/specs/reg/registration/functionality.js, test/specs/reg/registration/general.js, wdio.conf.js
https://jira.pasv.us/browse/RBTA-51
Added functionality tests for fields "password" and "confirm password"
=> RBTA-51/miks/registration-functionality-password

test/helpers/helpers.js
added 2 helpers to check if a field accepts 1 or multiple lines
=> helpers-text-fields-lines-number-check/trusevich

test/expected/login.js, test/selectors/login.js, test/specs/reg/login/general.js, wdio.conf.js
https://jira.pasv.us/browse/RBTA-16
=> RBTA-16/volodymyr-cherniak/login/forgot password link

package-lock.json, test/expected/filter-bar.js, test/helpers/filter-bar.js, test/selectors/filter-bar.js, test/specs/reg/filter-bar/functionality.js, wdio.conf.js
https://jira.pasv.us/browse/RBTA-92
I know that I shouldn't use browser.pause(), but I tried waitFor...() methods and my tests are failed in that case. I'm not sure what thing I can wait clicking on filters buttons. 
I try to use waitUntil() in the first test, but not sure neither that I do it right way.
=> RBTA-92/kharkova/Create tests for Filter Bar functionality

test/specs/reg/bug-report/edit-mode-.js
https://jira.pasv.us/browse/RBTA-96
Created tests for Bug report - Edit mode - Text Area.
=> RBTA-96/bug-report-edit-mode-text-area/kiparisova

test/expected/bug-report.js, test/selectors/bug-report.js, test/specs/reg/bug-report/edit-mode-.js, wdio.conf.js
https://jira.pasv.us/browse/RBTA-97
Created tests for Bug report - Edit mode - Drop-Downs.
=> RBTA-97/bug-report-edit-mode-drop-downs/kiparisova

test/specs/reg/registration/email-password-check.js
Fixed 2 test scripts. Everything is working.
=> Fix - registration-email-password-check

test/expected/login.js, test/specs/reg/login/general.js, wdio.conf.js
one test changed
one test added
=> Cherniak volodymyr/login/general/forgot password/little change

test/data/registration.js, test/specs/reg/registration/functionality.js
https://jira.pasv.us/browse/RBTA-50
added tests for registration functionality email and confirm email; 
added data for confirm email field
=> RBTA-50/registration-functionality-email/stepiko

test/expected/login.js, test/specs/reg/login/general.js, wdio.conf.js
https://jira.pasv.us/browse/RBTA-17
Added tests for login/general/login button
=> RBTA-17/login/general/login button/aliakseyeva

test/helpers/helpers.js, test/specs/reg/forgot-password/design.js, wdio.conf.js
-created 2 helpers to check vertical location of 2 and 3 elements to determine which elements are higher by their coordinates;
-updated forgot-password error location test by using this helper function
=> Vertical-location-check-helper-function/Trusevich

package-lock.json, test/specs/reg/registration/general.js
last name field font size verification completed and verified along with all existing tests
=> RBTA-147 last name field font size verification

test/expected/registration.js, test/specs/reg/registration/functionality.js, test/specs/reg/registration/general.js
Refer to the discussion in Slack
=> Fields validation without user registration based on Arthur comments

package-lock.json, test/specs/reg/registration/general.js
Verification of Registration Last Name font weight completed
=> RBTA-148 Verify that font weight: 400

test/expected/registration.js, test/specs/reg/registration/general.js
The font family verification implemented
=> RBTA-149/Verify-that-font-family-Segoe-UI/Last-Name-registration/polishchuk
